// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

#nullable disable

namespace Persistance.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220704160530_migration2")]
    partial class migration2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Model.Chat", b =>
                {
                    b.Property<Guid>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCreateDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdChat");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Model.Friend", b =>
                {
                    b.Property<Guid>("IdFriends")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeWhenRelacionWasCreated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUser1")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUser2")
                        .HasColumnType("TEXT");

                    b.HasKey("IdFriends");

                    b.HasIndex("IdUser1", "IdUser2")
                        .IsUnique();

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("Model.FriendRequest", b =>
                {
                    b.Property<Guid>("IdFriendRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTimeWhenRequestWasCreated")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromUser")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToUser")
                        .HasColumnType("TEXT");

                    b.HasKey("IdFriendRequest");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("Model.Message", b =>
                {
                    b.Property<Guid>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpedationDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOfShipper")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdChat", "ExpedationDate");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NrOfFriendRequests")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.UserInChat", b =>
                {
                    b.Property<Guid>("IdUserInChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewMessagesInChat")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUserInChat");

                    b.ToTable("UserInChats");
                });
#pragma warning restore 612, 618
        }
    }
}
