/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.16.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;


#nullable disable                // suppress C# 8.0 nullable contexts (we still support earlier versions)
#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace ThriftTechChat.Networking
{
  public static class ChatClientServerProjectExtensions
  {
    public static bool Equals(this List<global::ThriftTechChat.Networking.Chat> instance, object that)
    {
      if (!(that is List<global::ThriftTechChat.Networking.Chat> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::ThriftTechChat.Networking.Chat> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::ThriftTechChat.Networking.Chat> DeepCopy(this List<global::ThriftTechChat.Networking.Chat> source)
    {
      if (source == null)
        return null;

      var tmp291 = new List<global::ThriftTechChat.Networking.Chat>(source.Count);
      foreach (var elem in source)
        tmp291.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp291;
    }


    public static bool Equals(this List<global::ThriftTechChat.Networking.Message> instance, object that)
    {
      if (!(that is List<global::ThriftTechChat.Networking.Message> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::ThriftTechChat.Networking.Message> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::ThriftTechChat.Networking.Message> DeepCopy(this List<global::ThriftTechChat.Networking.Message> source)
    {
      if (source == null)
        return null;

      var tmp292 = new List<global::ThriftTechChat.Networking.Message>(source.Count);
      foreach (var elem in source)
        tmp292.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp292;
    }


    public static bool Equals(this List<global::ThriftTechChat.Networking.User> instance, object that)
    {
      if (!(that is List<global::ThriftTechChat.Networking.User> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::ThriftTechChat.Networking.User> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::ThriftTechChat.Networking.User> DeepCopy(this List<global::ThriftTechChat.Networking.User> source)
    {
      if (source == null)
        return null;

      var tmp293 = new List<global::ThriftTechChat.Networking.User>(source.Count);
      foreach (var elem in source)
        tmp293.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp293;
    }


    public static bool Equals(this List<global::ThriftTechChat.Networking.UserInChat> instance, object that)
    {
      if (!(that is List<global::ThriftTechChat.Networking.UserInChat> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::ThriftTechChat.Networking.UserInChat> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::ThriftTechChat.Networking.UserInChat> DeepCopy(this List<global::ThriftTechChat.Networking.UserInChat> source)
    {
      if (source == null)
        return null;

      var tmp294 = new List<global::ThriftTechChat.Networking.UserInChat>(source.Count);
      foreach (var elem in source)
        tmp294.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp294;
    }


  }
}
